stages:
    - build

variables:
    IMAGE_NAME: bahamut-automation

build:
    stage: build
    image: docker:latest
    services:
        - docker:dind
    before_script:
        - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
    script:
        - docker buildx create --use
        - docker buildx build --push --platform linux/arm64/v8,linux/amd64 -t $IMAGE_NAME:$CI_COMMIT_SHORT_SHA -t $IMAGE_NAME:dev .
