stages:
    - build
    - dev-deploy
    - deploy

variables:
    IMAGE_NAME: bahamut-automation

build:
    stage: build
    image: node:lts
    artifacts:
        paths:
            - dist/
            - scripts/
            - example/
            - package.json
            - pnpm-lock.yaml
    script:
        - npm i -g pnpm
        - pnpm i
        - pnpm build

dev-deploy:
    stage: dev-deploy
    image: docker:latest
    services:
        - docker:dind
    dependencies:
        - build
    before_script:
        - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
    script:
        - docker buildx create --use
        - ./scripts/docker_dev.sh

deploy:
    stage: deploy
    only:
        - tags
    image: docker:latest
    services:
        - docker:dind
    dependencies:
        - build
    before_script:
        - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
    script:
        - docker buildx create --use
        - ./scripts/docker_release.sh
