stages:
    - build
    - dev-deploy
    - deploy

variables:
    IMAGE_NAME: bahamut-automation

build:
    stage: build
    image: node:lts
    artifacts:
        paths:
            - dist/
    script:
        - npm i -g pnpm
        - pnpm i
        - pnpm build

dev-deploy:
    stage: dev-deploy
    image: docker:git
    services:
        - docker:dind
    dependencies:
        - build
    before_script:
        - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
    script:
        - git checkout main
        - docker buildx create --use
        - ./scripts/docker_dev.sh

deploy:
    stage: deploy
    only:
        - tags
    image: docker:git
    services:
        - docker:dind
    dependencies:
        - build
    before_script:
        - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
    script:
        - git checkout main
        - docker buildx create --use
        - ./scripts/docker_release.sh

deploy-npm:
    stage: deploy
    only:
        - tags
    image: node:lts
    dependencies:
        - build
    script:
        - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
        - npm publish --access public
