name: "Bahamut Automation"
description: "巴哈姆特自動化！"
inputs:
  username:
    description: "巴哈姆特帳號 (建議使用 Secret)"
    required: true
    default: ""
  password:
    description: "巴哈姆特密碼 (建議使用 Secret)"
    required: true
    default: ""
  auto_sign:
    description: "啟用自動簽到"
    required: true
    default: "false"
  auto_sign_double:
    description: "啟用自動觀看雙倍簽到獎勵廣告"
    required: false
    default: "false"
  auto_draw:
    description: "啟用福利社自動抽抽樂"
    required: true
    default: "false"
  auto_answer_anime:
    description: "啟用動畫瘋自動答題"
    required: true
    default: "false"
runs:
  using: "node12"
  main: "action.bundled.js"
