version: 2.1

orbs:
  node: circleci/node@4.7.0
  browser-tools: circleci/browser-tools@1.1.3

jobs:
  automation:
    docker:
      - image: cimg/node:16.6

    steps:
      - checkout
      - browser-tools/install-chrome
      - run:
          command: |
            google-chrome --version
            node --version
          name: Check Versions
      - run:
          command: |
            npm i
          name: Install NPM Packages
      - run:
          command: |
            node CircleCI.js $MODULES $SECRETS $PARAMETERS
          name: Run Automation

workflows:
  run_automation:
    jobs:
      - automation