name: Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_action:
    name: Build Action
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install Packages
        run: npm install
      - name: Build Action
        run: node scripts/build_action.js
      - name: Commit
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: "./action"
          user_name: "JacobLinCool"
          user_email: "jacoblincool@users.noreply.github.com"
          publish_branch: "action"
          commit_message: "CircleCI Ignore: [ci skip]"

  build_binary:
    name: Build Binary
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install Packages
        run: npm install
      - name: Build Binary
        run: node scripts/build_binary.js
      - name: Commit
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: "./dist"
          user_name: "JacobLinCool"
          user_email: "jacoblincool@users.noreply.github.com"
          publish_branch: "binary"
          commit_message: "CircleCI Ignore: [ci skip]"
